resources:
  containers:
  - container: a2godockerimage
    #image: mcr.microsoft.com/mlops/python:latest
    image: a2go/diabetes_regression
    endpoint: acrconnection

pool:
  vmImage: ubuntu-latest
  
stages:
- stage: 'Create_Model'
  displayName: 'Create Model'
  jobs:
    - job: "Run_Python_Main"
      displayName: "Run_Python_Main"
      container: a2godockerimage
      timeoutInMinutes: 0
      steps:
        -  task: AzureCli@1
           inputs:
              azureSubscription: 'ws-connection'
              scriptLocation: inlineScript
              workingDirectory: $(Build.SourcesDirectory)
              inlineScript: |
                set -e # fail on error
                export SUBSCRIPTION_ID=$(az account show --query id -o tsv)
                echo "foiiii"
                echo $PWD
                cd /app
                python -m src.main
           displayName: 'Publish Azure Machine Learning Pipeline'
        