name: mlops_diabetes_regression_basic
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - pip:
    - pytest==5.4.*
    - pytest-cov==2.8.*
    - requests==2.23.*
    - python-dotenv==0.12.*
    - flake8==3.7.*
    - flake8_formatter_junit_xml==0.0.*
    - azure-cli==2.3.*
    - train
    - pandas==1.1.5
    - azureml-sdk==1.32.0
    - scikit-learn
    - azureml==0.2.7
    - azureml-core==1.32.0
    - azureml-pipeline==1.32.0
    - azureml-pipeline-core==1.32.0
    - azureml-pipeline-steps==1.32.0
    - python-dotenv==0.19.0
    